font=CaskaydiaCove Nerd Font:size=16
terminal=foot -e

prompt="󱂬  "
placeholder="Type to search clipboard"

layer=overlay
dpi-aware=no
icons=yes

lines=10
width=58

inner-pad=16
horizontal-pad=28
vertical-pad=20

line-height=36
match-counter=yes

[border]
radius=22
width=2

[colors]
background=0A0F0Fee

text=DCE8E6dd
input=DCE8E6dd
prompt=8FDED3dd

placeholder=6D7876ff
counter=6D7876ff

match=B8FFF1ff

selection=1B2120ff
selection-text=E9FFFFdd
selection-match=B8FFF1ff

# border=8FDED355